# Generated by Django 5.0.3 on 2024-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type", models.CharField(max_length=255)),
                ("Rotational_speed_rpm", models.IntegerField(default=0)),
                ("Torque_Nm", models.IntegerField(default=0)),
                ("Tool_wear_min", models.IntegerField(default=0)),
                ("Machine_failure", models.IntegerField(default=0)),
                ("TWF", models.IntegerField(default=0)),
                ("HDF", models.IntegerField(default=0)),
                ("PWF", models.IntegerField(default=0)),
                ("OSF", models.IntegerField(default=0)),
                ("RNF", models.IntegerField(default=0)),
                ("type_of_failure", models.CharField(max_length=255)),
                ("Air_temperature", models.IntegerField(default=0)),
                ("Process_temperature", models.IntegerField(default=0)),
            ],
        ),
    ]
